# Git aliases, shared by bash AND zsh. Sourced by shell/aliases.sh.
# Keep POSIX-friendly: no zsh-only syntax.

# Git
alias gcl='git clone --recursive'
alias gcf='git config'
alias gs='git status'
alias gst='git status-short'
alias ga='git add'
alias gaa='git add -A'
alias gmv='git mv'
alias grm='git rm'
alias gl='git log'
alias gls='git log --stat' ## include which files were altered
alias glp='git log -p' ## display the full diff of each commit
alias gll='git pretty-log'
alias gbl='git blame -b -w'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdw='git diff --word-diff'
alias gdcw='git diff --cached --word-diff'
alias gw='git whatchanged'
alias gg='git grep -n -C2 -E'
alias gc='git commit -v'
alias gc!='git commit -v --amend'
alias gcu='git reset --soft HEAD~' ## undo commit
alias gcm='git commit -m'
alias gca='git commit -a'
alias gcam='git commit -a -m'
alias gb='git branch'
alias gbs='git branch --sort=committerdate'
alias gbm='git branch --merged'
alias gbr='git branch -r'
alias gbu='git remote update origin --prune' ## update remote list
alias gm='git merge'
alias gms='git merge --squash'
alias gmm='git merge -m'
alias gt='git tag'
alias gco='git checkout'
alias gcom='git checkout master'
alias gcop='git checkout preprod'
alias gcor='git checkout recette'
alias gf='git fetch'
alias gfo='git fetch origin'
alias gp='git pull'
alias gpull='git pull'
alias gpush='git push'
alias gpr='git pull --rebase'
alias gsu='git set-upstream'
alias gget='git get'
alias gput='git put'
alias ggp='git get-put'
alias grb='git rebase'
alias gss='git stash save'
alias gsa='git stash apply'
alias gsp='git stash pop'
alias gsl='git stash list'
alias ggc='git gc --aggressive'
