# Keyboard shortcuts cheatsheet
### <Ctrl> + <q> then <c> : Create a new term
### <Ctrl> + <q> then [X] : Choose a specifid term (where [X] is the term number)

# Remap prefix to ctrl-q
unbind C-b
set -g prefix C-q

# Set window and pane index to 1 (0 by default)
set -g base-index 1
set -g pane-base-index 1

# True colors terminal
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"

# Allow mouse usage
set -g mouse on

# act like vim
setw -g mode-keys vi

# Keybindings
# Reload config with a key
bind     r     source-file ~/.tmux.conf \; display "Config reloaded!"
bind     a     split-window -c "#{pane_current_path}"
bind     q     split-window -h -c "#{pane_current_path}"
bind     up    select-pane -U
bind     right select-pane -R
bind     left  select-pane -L
bind     down  select-pane -D

# copying selection vim style
bind-key v     copy-mode
bind-key p     paste-buffer
bind-key -T copy-mode-vi C-Left  send-keys -X previous-word
bind-key -T copy-mode-vi C-Right send-keys -X next-word
bind-key -T copy-mode-vi Escape  send-keys -X cancel
bind-key -T copy-mode-vi v       send-keys -X begin-selection
bind-key -T copy-mode-vi V       send-keys -X select-line
bind-key -T copy-mode-vi r       send-keys -X rectangle-toggle
if-shell "command -v pbcopy" {
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
} {
    bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
}
