eval "`dircolors`"

if [ -f "$HOME/dotfiles/public/zsh/aliases.zsh" ]; then
    source "$HOME/dotfiles/public/zsh/aliases.zsh"
fi

shopt -s autocd                  # A command name that is the name of a directory is executed as if it were the argument to the cd command
shopt -s dirspell                # Bash attempts spelling correction on directory names during word completion if the directory name initially supplied does not exist.
shopt -s nocaseglob              # Bash matches filenames in a case-insensitive fashion when performing filename expansion.
shopt -s cdspell                 # Correct cd typos
shopt -s histappend              # Append History instead of overwriting file
shopt -s cmdhist                 # Bash attempts to save all lines of a multiple-line command in the same history entry
shopt -s extglob                 # Extended pattern
shopt -s no_empty_cmd_completion # No empty completion

BLACK="\[\e[30m\]"
RED="\[\e[31m\]"
GREEN="\[\e[32m\]"
YELLOW="\[\e[33m\]"
BLUE="\[\e[34m\]"
MAGENTA="\[\e[35m\]"
CYAN="\[\e[36m\]"
WHITE="\[\e[97m\]"
NONE="\[\e[0m\]"

mkdir -p "$HOME/.cache"

export HISTFILE="$HOME/.cache/bash_history"
export LESSHISTFILE=-
export MYSQL_HISTFILE=/dev/null

export PS1="[${WHITE}\u${NONE}@${RED}\h${NONE} ${CYAN}\w${NONE}]\\$\[$(tput sgr0)\] "
export VISUAL='vim'
export EDITOR='vim'

